Inc1-4Review
Pashteto/yp_inc1 pull request #1
Opened 2021-08-30 08:07 UTC by Pashteto

1st day

2021-08-31 21:17 UTC, Barugoo commented on handlers/handlers.go
> +	}
Нет нужды дополнительно проверять метод внутри тела хэндлеров, если используешь роутер
```go
r.HandleFunc("/", sshand.PostHandler).Methods("POST")    //routing post
```
Здесь ты уже "сказал" серверу, что запросы, удовлетворяющие такому маршруту и с таким http-методов должны проваливаться в метод .PostHandler. Запросы с другим методом туда не попадут)

2021-08-31 21:20 UTC, Barugoo commented on handlers/handlers.go
>  }
Круто, что ты заморочился, но мне кажется такой статус вводит в заблуждение. Если с клиентом не было обговорено иное, он в первую очередь будет смотреть на статус-код (`400` в данном случае). `Bad Request`  сервер обычно возвращает, например, если ему пришло неверное тело запроса. Для случая `Method Not Allowed` существует отдельный статус 405 Method Not Allowed

2021-08-31 21:23 UTC, Barugoo commented on handlers/handlers.go
> +		http.Error(w, "DB not resonding", http.StatusBadRequest)
Кейсу `DB not responding` все же больше подходит статус `http.StatusInternalServerError`

2021-08-31 21:24 UTC, Barugoo commented on handlers/handlers.go
> +		w.Header().Set("Content-Type", "text/html")
Это делать необязательно, достаточно ограничиться редиректом)

2021-08-31 21:26 UTC, Barugoo commented on handlers/handlers.go
>  	defer r.Body.Close()
Лайк за то, что подумал про закрытие тела, но вообще это делать необязательно. `http.Server` это делает самостоятельно под капотом:
```go
// The Server will close the request body. The ServeHTTP
// Handler does not need to.
```
Дока: https://golang.org/pkg/net/http/#Request

2021-08-31 21:28 UTC, Barugoo commented on handlers/handlers.go
> +	strbody := string(body)
Я бы это делал после проверки ошибки на `nil`
Есть такое простое правило в Go: если тебе вернулась ошибка из функции (например,`ioutil.ReadAll` (кстати обнови Go, теперь это делает пакет `io`)), нет смысла работать с тем, что вернулось в остальных значениях (в данном случае -- в `body`)

2021-08-31 21:33 UTC, Barugoo commented on handlers/handlers.go
>  		fmt.Println(err)
Здесь я бы сделал:
```go
if err != nil {
    log.Println(err)
    http.Error(w, "unable to parse body", http.StatusBadRequest)
    return
}
```
Тк нам нет смысла работать с запросом дальше, если тело неудалось распарсить. Просто выходим из функции, вызвав директиву `return`
Это также позволит нам избавиться от необходимости использовать `else` на 71-ой строке

2021-08-31 21:34 UTC, Barugoo commented on main.go
>  	signal.Notify(sigint, os.Interrupt)
Graceful Shutdown одобряем

2021-08-31 21:37 UTC, Barugoo commented on handlers/handlers.go
> +			shorturl = "http://localhost/" + id
Хотелось бы иметь возможность конфигурировать адрес сервера, который ты здесь подставляешь, чтобы при локальных тестах и при запуске на боевом окружении он здесь был разный. Также у тебя может доступ быть только протоколу `https`,  поэтому конфигурируемый адрес должен включать в себя и протокол.

2021-08-31 21:38 UTC, Barugoo commented on handlers/handlers.go
> +		return err
-> `return errors.New("No Redis DB")`

2021-08-31 21:38 UTC, Barugoo requested changes
Круто, но есть куда расти) Жду доработанную версию!

2021-09-01 22:50 UTC, Barugoo commented on handlers/handlers.go
> +		http.Error(w, "No URL recieved", http.StatusBadRequest)
Здесь `return`

2021-09-01 22:52 UTC, Barugoo commented on main.go
> +	//	r.HandleFunc("/", sshand.HandlerBadRequest)              //routing others as Bad requests
Убираем закомментированный код из репозитория. Если у тебя есть неактуальный функционал лучше его удалить (ты всегда его можешь восстановить из старых коммитов), чтобы не плодить мусор и не дизоринтировать читающего код человека)

2021-09-01 22:56 UTC, Barugoo commented on handlers/handlers.go
> +		if !strings.Contains(strbody, "http:") && !strings.Contains(strbody, "https:") {
В пакете `strings` есть специаальная функция `HasPrefix` которая проверяет вхождение строки именно вначале проверяемой строки. В твоем случае `strings.Contains` вернет `true` для такой строки: `https://some.addr.http:8080/` и ты проставишь неверный протокол.

2021-09-01 22:56 UTC, Barugoo commented on handlers/handlers.go
> +		if !strings.Contains(strbody, "http:") && !strings.Contains(strbody, "https:") {
Вообще валидацию урла лучше всего делать через пакет `net/url` и функцию `url.Parse`

2021-09-01 22:58 UTC, Barugoo commented on handlers/handlers.go
> +		hostName := hostProto + strings.Split(r.Host, ":")[0]
Я так понял это конфигурация протокола которую я рекомендовал добавить. На самом деле все проще - ты можешь пробрасывать эту информацию в конфиге, публичный адрес и протокол у тебя зачастую статичны и их не надо динамически вытаскивать из каждого запроса. 
То есть просто добавь подстановку сюда из конфига строки вида `http://localhost`

2021-09-01 23:00 UTC, Barugoo commented on handlers/handlers.go
> +		http.Error(w, "No URL recieved", http.StatusBadRequest)
Вообще здесь можно избавиться от `else`, что я тебе советую делать всегда (а ты всегда от него можешь избавиться в логике)
То бишь:
```go
if len(strBody) == 0 {
    http.Error(w, "No URL recieved", http.StatusBadRequest)
    return
}

if !strings.Contains(strbody, "http:") && !strings.Contains(strbody, "https:") {
// и тд
```

2021-09-01 23:02 UTC, Barugoo requested changes
Добавил еще несколько комментариев. Еще в репе нет тестов, актуализируй мастер с шаблоном, должны появится файлы конфигурации github actions. Если что-то не получается - пиши в чатик подгруппы, разрулим

2021-09-01 23:44 UTC, Pashteto commented on handlers/handlers.go
> +		if !strings.Contains(strbody, "http:") && !strings.Contains(strbody, "https:") {
я хотел найти такую функцию валидации урла и не нашел:)

2021-09-02 15:23 UTC, scukonick commented on handlers/handlers.go
> +func (h *HandlersWithDBStore) GetHandler(w http.ResponseWriter, r *http.Request) {
Я бы во всех хендлерах использовал:
```go
ctx := r.Context()
```
Этот контекст будет канселиться гошкой в случае, если клиент отвалился, и тогда ты сможешь завершить все операции, чтоб они не работали вхолостую. Ну и вообще миддлвари всякие часто в этот контекст полезные штуки кладут, которые надо передавать дальше по стеку

2021-09-03 17:30 UTC, Barugoo commented on cmd/shortener/main.go
> +		log.Println(os.Getenv("APP_BASE_URL"))*/
Комментированный код убираем) 
Кстати логгировать конфиг, с которым у тебя запустилась приложенька это действительно хорошая практика, так что я бы просто раскоментил этот код. Ах да, на всякий случай: НИКОГДА не свети токены доступа в логах (здесь у тебя их нет).

2021-09-03 17:30 UTC, Barugoo commented on cmd/shortener/main.go
> +	conf.RecieveEnv(os.Getenv("APP_BASE_HOST"), os.Getenv("APP_PORT"), os.Getenv("APP_BASE_URL"))
Для читабельности я бы использовал такую запись:
```go
conf.ReceiveEnv(
    os.Getenv("APP_BASE_HOST"),
    os.Getenv("APP_PORT"),
    os.Getenv("APP_BASE_URL"),
)
```

2021-09-03 17:32 UTC, Barugoo commented on cmd/shortener/main.go
> +	conf.RecieveEnv(os.Getenv("APP_BASE_HOST"), os.Getenv("APP_PORT"), os.Getenv("APP_BASE_URL"))
Подумай, а что если у нас будет не три поля в конфиге, а тридцать? Не делать же `ReceiveEnv` методом с тридцатью аргументами) Может быть лучше не передавать аргументы вовсе а внутри нее делать `os.Getenv`?

2021-09-16 12:16 UTC, Barugoo commented on cmd/shortener/main.go
> +	log.Println("\nFlags input:\nSERVER_ADDRESS,\tBASE_URL,\tFILE_STORAGE_PATH:\n", *ServAddrPtr, ",", *BaseURLPtr, ",", *FStorPathPtr)
Логгировлать переданный конфиг при запуске это хорошая практика, главное помни чтобы туда не попали токены доступов)

2021-09-16 12:16 UTC, Barugoo commented on cmd/shortener/main.go
> +	log.Println("\nFlags input:\nSERVER_ADDRESS,\tBASE_URL,\tFILE_STORAGE_PATH:\n", *ServAddrPtr, ",", *BaseURLPtr, ",", *FStorPathPtr)
Кстати \n в начале лишний, по идее

2021-09-16 12:24 UTC, Barugoo commented on config/config.go
> +		os.Setenv("REDIS_HOST", *RedisPtr)
А зачем, если не секрет, тебе править эту переменную окружения из приложения?

2021-09-16 12:24 UTC, Barugoo commented on config/config.go
> +		os.Setenv("REDIS_HOST", *RedisPtr)
Отпиши потом в личку, я боюсь шо забуду посмотреть твой ответ здесь

2021-09-16 12:28 UTC, Barugoo commented on config/config.go
> +			return
Нетнетнет, так делать не надо
Да, в Го есть замечательная возможность именовать возвращаемые значения, из этого вытекает тот функционал, который ты на этой строке используешь. Но его использовать я крайне не рекомендую.
По моему опыту общепринятое мнение такое: нужно ВСЕГДА указывать переменные после `return` которые ты хочешь вернуть. 
Иначе очень сильно ухудшается восприятие кода, тк для того чтобы понять какое значение вернется из функции, нужно смотреть всю внутреннюю логику и пытаться понять, где и в какой момент переменной именованного возвращаемого значения было что-то присвоено. 
Лучше просто делать `return false, errors.New("SERVER_ADDRESS, BASE_URL flags error")` независимо от того, используешь ты именованы значения или нет.

2021-09-16 12:32 UTC, Barugoo commented on config/config.go
> +	}
А почему здесь так? Может показаться, что эти две конфигурации связаны, но на самом деле адрес и порт, по которому стучится к тебе пользователь может кардинально отличаться от того адреса и порта, на котором крутится сервер в реальности. Между конечным клиентом (браузером, мобильным приложением, другим сервисом) и сервером, где у тебя физически обрабатывается запрос (то бишь тот, который ты пишешь) может быть миллион проксей, веб серверов, dns'ов и так далее. 

tl;dr порт на котором запускается сервер и адрес по которому стучится пользователь для получения полного урла в реальности никак между собой не связаны и должны быть абсолютно независимыми частями конфига.

2021-09-16 12:35 UTC, Barugoo commented on config/config.go
> +	}
Если хочешь можем обсудить подробнее на 1-он-1 )

2021-09-16 12:41 UTC, Barugoo commented on cmd/shortener/main.go
> +	server.Shutdown(ctx)
Поправь меня, если я не прав, но этот код никогда не выполнится
У тебя запуск сервера блокирует горутину на 80 строке

2021-09-16 12:42 UTC, Barugoo commented on cmd/shortener/main.go
> +		log.Printf("BASE_URL error:\t%+v", err)
Почему именно `BASE_URL error`? Представь, что ты ничего не знаешь о внутренней логике conf.UpdateByFlags, откуда ты знаешь шо проблема именно с BASE_URL'ом из всех переданных переменных? 

Логи лучше писать так, будто ты ничего не знаешь о содержимом функции, которая вернула ошибку

2021-09-16 12:44 UTC, Barugoo commented on filed_history/filehist.go
> +func NewFReaderSlice(fileName string) (*fReaderSlice, error) {
А зачем нам понадобилась отдельная идентичная структура для методов, которые возвращают слайд? Разве мы не можем эти методы навесить на одну и ту же структуру?

2021-09-16 12:46 UTC, Barugoo commented on handlers/handlers.go
> +	filedb.WriteAll(h.Rdb, *h.Conf)
Конкурентная запись в файл здесь

2021-09-16 12:53 UTC, Barugoo commented on filed_history/filehist.go
> +	keys, err := (*rdb).ListAllKeys(ctx)
Чтобы не делать `(*rdb)` достаточно передавать интерфейс repos.SetterGetter в функцию по значению)
Интерфейсы под капотом сами по себе ссылочные типы и мы никогда не работаем с ними по указателю, только по ссылке

2021-09-16 12:54 UTC, Barugoo requested changes
Круто, но есть замечания. Самое главное - конкурентная запись в файл, надо разрулить.

2021-09-16 19:05 UTC, Barugoo commented on handlers/handlers.go
> +		http.Error(w, "unable to marshall short URL", http.StatusServiceUnavailable)
Я бы здесь использовал все же http.StatusInternalServerError

2021-09-16 19:13 UTC, Barugoo commented on handlers/handlers.go
> +	errReadDB := h.pingRedisDB(h.Rdb)
Пинговать redis при обработке каждого запроса излишне. Достаточно сделать это один раз при первоначальном подключении. Если соединение с редисом порвется ты об этом итак узнаешь при попытке записать или вычитать что-то из него

2021-09-16 19:16 UTC, Barugoo commented on handlers/handlers.go
> +func (t *typeHandlingURL) UnmarshalJSON(data []byte) error {
О! Круто, что ты реализовал свой маршалер, автоматическое преобразоваание сырых данных в гошные типы (time.Time еще отличный пример) это один из самых популярных кейсов

2021-09-19 21:43 UTC, Barugoo commented on cmd/shortener/main.go
> +		log.Fatal(err, repa)
Можно поменять на:
```go
log.Fatalf("file exited; err: %v; rep: %v", err, repa)
```

2021-09-19 21:47 UTC, Barugoo requested changes
Привет! Слушай, я отправил комментарий на портале, но хочу дополнить: пожалуйста, если тебя не затруднит, сделай отдельные PR под каждую домашку, тк здесь сейчас куча комментариев с первых трех инкрементов и это немного неудобно ревьювить. 
Что касается этого трая я не увидел правок по комментам, которые я оставлял (могу ошибаться, поправь пожалуйста, если это не таК) поэтому я отправил на переделку.

2026-07-17 16:21 UTC, closed without merging